version: "3.9"

services:
  backend:
    build:
      context: .
      args:
        - DEV=true
    container_name: backend_recipe_app
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    command: python manage.py runserver 0.0.0.0:8000
