version: "3.9"

services:

  backend:
    build:
      context: .
    container_name: backend_recipe_app
    restart: always
    volumes:
      - static-data:/app/vol/web
    env_file:
      - ./core/.env
    depends_on:
      - db_postgresql

  db_postgresql:
    image: postgres
    container_name: db_postgresql_recipe_app
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  proxy_nginx:
    build:
      context: ./proxy
    container_name: proxy_nginx_recipe_app
    restart: always
    ports:
      - "80:8000"
    volumes:
      - static-data:/vol/static
    depends_on:
      - backend

volumes:
  postgres_data:
  static-data: