version: "3.9"

services:

  db_postgresql:
    image: postgres
    container_name: db_postgresql_recipe_app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: .
      args:
        - DEV=true
    container_name: backend_recipe_app
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
      - static-data:/app/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./core/.env
    depends_on:
      - db_postgresql


volumes:
  postgres_data:
  static-data: