# Generated by Django 3.2.18 on 2023-04-08 11:11

import config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20230402_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=config.models.recipe_image_file_path),
        ),
    ]
